### ISSUE TITLE
Text line recognition

### ISSUE THREAD

**Issue by sanakhamekhem** [emedvedev/attention-ocr#1]
Hello,
I would like to use this toolkit to recognize text line image,  the groundtruth is like the following example:
aaAlaBeeE  maBalMaaEtaA  maBnaE  aaAlaBseMnaM..........................
**aaAlaBeeE**  is a word composed from this forms/letters : **aaA laB eeE** 
How can I adapt this annotation to that is used in this framework like the following: 
datasets/images/hello.jpg **hello**
datasets/images/world.jpg **world**

**Comment by emedvedev** [comment]
Hi,

The characters of the labels are encoded into int32 symbols (i.e. `A=1`, `B=2`). The encoding is happening [here](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/data_gen.py#L78), and the decoding map for inference is [here](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L24). You can modify both the encoding and the decoding so that your labels would be converted to symbols not by single characters, but by your combinations. Instead of `A=1`, `B=2` you should have something like `aaA = 1`, `laB = 2`, etc. That's not very easy, but should work.

Alternatively, if your charset length (the entire list of `aaA`, `laB`, `eeE`, etc.) is 36 elements or less, you can simply substitute them for single alphanumeric characters in the annotations document. Given your example, I suppose you have more elements though.
