### ISSUE TITLE
Trouble trying using the exported .pb frozen graph

### ISSUE THREAD

**Issue by Rayndell** [emedvedev/attention-ocr#102]
Hello,

I was wondering if you have already been able to test the exported .pb files (especially the frozen graph) within the C++ TensorFlow API?

In short, I recently developed some tools to use the typical TensorFlow exported frozen graph for classification problems and they work. I tried using them with the .pb file I exported with your provided tools, and kept producing 0 outputs (without crashes). I checked the output and input layer names and they are the same in my program and the .pb file. This is what I've done so far:

In your code, I changed the "input_image_as_bytes" input, so that instead of expecting png data it expects already decoded image data (i.e. I deleted the decode_png step and simply added a input with shape [None, None, 3] as placeholder). It doesn't seem to produce any output when I try to retrieve the "prediction" layer.

Si if you have any insights about how to use it that would be very helpful.

Thanks,
Aurélien

**Comment by emedvedev** [comment]
I don’t have any insights right off the bat, so anything else you could try might help.

Have you tried the Saved Model? Does it work, or is there no result as well?

**Comment by Rayndell** [comment]
Actually I tried to export the saved model, and freeze the graph with the standard TensorFlow "freeze_graph.py" tool: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

When this program tries to read the saved_model.pb file a reading error pops up (both in binary and text format, but the error is different). Here are the errors:

In binary format: google.protobuf.message.DecodeError: Truncated message.

In text format: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 3: invalid continuation byte

It seems that TensorFlow (at least the current version) is not able to read your .pb files. Is it possible that it might be incompatible with the current version of the protobuf library?

**Comment by Rayndell** [comment]
OK, some update here is needed. I was able to make things work.

Basically, I created my own Python script to export a .pb file with the input I needed (i.e. an already decoded image instead of a filename). I simply copied/pasted the code contained in model.py (the constructor of the Model class and the prepare_image method) and modified it to use it as a function instead of a class. This function takes the input (a 3-dimensional tensor which contains the image data) and the model parameters (same as yours) and produces the prediction and probability input nodes. I then wrapped this function call into the standard TensorFlow export tools and this produces a .pb saved model. I rthen use the standard TensorFlow freeze-graph tools with the checkpoint produced by your training program, and the final .pb I obtain works with the TensorFlow C++ API.

I think the problem resides in the method you used in your exporter class, but I wasn't able to locate the error source. I can provide the Python export script if it can be helpful.

**Comment by emedvedev** [comment]
Please do, that would actually be super useful. I'll look at the working
script and try to figure out what the difference is.


On July 9, 2018 at 16:50:44, Rayndell (notifications@github.com) wrote:

OK, some update here is needed. I was able to make things work.

Basically, I created my own Python script to export a .pb file with the
input I needed (i.e. an already decoded image instead of a filename). I
simply copied/pasted the code contained in model.py (the constructor of the
Model class and the prepare_image method) and modified it to use it as a
function instead of a class. This function takes the input (a 3-dimensional
tensor which contains the image data) and the model parameters (same as
yours) and produces the prediction and probability input nodes. I then
wrapped this function call into the standard TensorFlow export tools and
this produces a .pb saved model. I rthen use the standard TensorFlow
freeze-graph tools with the checkpoint produced by your training program,
and the final .pb I obtain works with the TensorFlow C++ API.

I think the problem resides in the method you used in your exporter class,
but I wasn't able to locate the error source. I can provide the Python
export script if it can be helpful.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/emedvedev/attention-ocr/issues/102#issuecomment-403506086>,
or mute the thread

**Comment by Rayndell** [comment]
Here it is.

The interesting part is located between lines 214 and 236, where I create a placeholder for my data, pass it to the build_graph function with the model parameters, and create an output node for each of the prediction and probability nodes. Afterwards I serialize the graph def in a pretty standard way.

[export-graph.zip](https://github.com/emedvedev/attention-ocr/files/2176705/export-graph.zip)

**Comment by ShiyangZhang** [comment]
hi, @Rayndell 
  follow your step, i got a wrong output  ['0000000', 0.5003086850925088] by the following code . not sure why. Do you have any suggestion?
  `from skimage import io, transform
import cv2
def recognize(jpg_path, pb_file_path):
    with tf.Graph().as_default():
        output_graph_def = tf.GraphDef()

        with open(pb_file_path, "rb") as f:
            output_graph_def.ParseFromString(f.read())
            _ = tf.import_graph_def(output_graph_def, name="")

        with tf.Session() as sess:
            #init = tf.global_variables_initializer()
            #sess.run(init)

            input_x = sess.graph.get_tensor_by_name("input:0")
            print("sess.graph", sess.graph)
            print("input_x", input_x)
            out_softmax = sess.graph.get_tensor_by_name("prediction:0")
            print (out_softmax)
            out_label = sess.graph.get_tensor_by_name("probability:0")
            print(out_label)

            img = io.imread(jpg_path)

            height = 32
            width = 128
            #io.imwrite("a.jpg", img)
            img = transform.resize(img, (height, width, 3))
  
            img_out_softmax = sess.run([out_softmax,out_label], feed_dict={input_x:np.reshape(img, [height, width, 3])})
            

    
    
          
            print ("img_out_softmax: ", img_out_softmax)


recognize("./1_000809.jpg", "./freeze_graph.pb")`
