### ISSUE TITLE
Do I have to resize the image to fixed size at first before generating tfrecords data for training or testing?

### ISSUE THREAD

**Issue by wenston2006** [emedvedev/attention-ocr#141]
I noticed that in the code 'dataset.py' one training( or testing) image is read as data of bytes type. There seems to be no information about image width and height during the process of generating tfrecords. So do I have to resize the training or testing image to fixed size at first?

**Comment by emedvedev** [comment]
You can have images of any size in the dataset. Uniform size would work much better for training and recognition though, and don’t forget to set the `max-width` and `max-height` params during training.

**Comment by wenston2006** [comment]
Thanks for your reply!Can you give any advice on Chinese ocr training? My aim is to recognize the Chinese characters in an image. I have tried encoding the Chinese character as utf-8 since Chinese characters are not supported by Latin-1. But the utf-8 type would take 3-4 bytes. In my opinion the label of one character should take just one bytes. So what should I do? Can I tansform the label as a numeric value such as the index of one character in the character dictionary?

**Comment by emedvedev** [comment]
You might want to look into extending the [charmap](https://github.com/emedvedev/attention-ocr/blob/master/aocr/util/data_gen.py#L23) instead. Take a look at `model.py` to understand how it's used, and at the `full-ascii` flag to have an example of extending it, and then I think it shouldn't be difficult to introduce Chinese characters into it either.

There might be some unexpected issues with Unicode during both dataset generation and model work, but nothing unsurmountable, so good luck! I'm going to close this issue, since I can only help with errors in my code, not with modifications, but please feel free to submit a pull request if you make any progress with Unicode!
