### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by pribadihcr** [emedvedev/attention-ocr#30]
Hi @emedvedev,

Where to download the pretrained model?

Thanks

**Comment by thisismohitgupta** [comment]
can you provide a pretrained model?  it would be really helpful.

**Comment by emedvedev** [comment]
> can you provide a pretrained model?

It really depends on what you mean by that. To achieve good results, your training dataset should be as close as possible to the data you're going to be using the model on, so I can't really provide a pre-trained model: it should be trained according to your use case.

The model can be easily trained in Google Cloud Platform for free though: it provides a generous amount of trial credits.

One thing that could be helpful is training the model on one of the known datasets (like Synth90k), and if you end up doing that, please submit a PR, it could actually be helpful. I've had one of the previous versions trained on this dataset, but we've changed the model since then, so the weights would not be valid now.

Closing the issue, since "providing a pre-trained model" is really too broad. Sorry I couldn't be of much help, folks!
