### ISSUE TITLE
optionally save filename as comment field in dataset

### ISSUE THREAD

**Issue by ckirmse** [emedvedev/attention-ocr#41]
Right now, if you have a large corpus for training, many of which have the exact same text, it is painful to figure out which one is responsible for a low value in output of the 'test' command.

Proposed solution: save the original filename with the record and output that in testing.

Thoughts?

**Comment by emedvedev** [comment]
I think it could be a good idea, although instead of having a `filename` field, we can probably name it `comment` to be a bit more generic, and save the filenames there with a CLI option during dataset generation. During the testing, if `comment` is present, it can be output when the comparison is not correct.

What do you think about that?

**Comment by ckirmse** [comment]
Works for me. I'll probably do this before I do another training run if no one else gets to it first.
