### ISSUE TITLE
unrecognized arguments: --attn-use-lstm=False

### ISSUE THREAD

**Issue by feygina** [emedvedev/attention-ocr#58]
The same problem with gpu-id. Can you please explain me how to set parameters. I didn't have problems with --max-width, --max-height, --max-prediction, --full-ascii, and --color.  Thanks!

**Comment by emedvedev** [comment]
`attn-use-lstm` has actually been removed a while ago: LSTM is used by default, and you can specify `use-gru` if you want GRU instead. Updated the README to reflect that.

Setting parameters was a bit weird, since some parameters, like `gpu-id`, were global, and others were specific to subcommands. The default `argparse` syntax is `aocr [global] train [local]`, but it's confusing as hell, so I've just pushed a new version. 

Updating to 0.6.0 (or master) should fix your issue: you should be able to use `gpu-id` with the other parameters now.

**Comment by feygina** [comment]
Thanks for your answer and update @emedvedev !

**Comment by emedvedev** [comment]
You're welcome! Glad you like the project :)
