### ISSUE TITLE
Recognize arbitrary length string

### ISSUE THREAD

**Issue by subhadeepdas91** [emedvedev/attention-ocr#8]
Hi,
I have followed the steps and successfully trained a machine to recognize characters from 0 to 9, 
Currently it is able to recognize images with a single character, but unable to recognize arbitrary length of characters,
Please suggest me a way to make the OCR recognize arbitrary length of characters and properly arrange them as per the image

**Comment by emedvedev** [comment]
Hi,

Aside from training character recognition, you also need to train the attention part of the model. That means that if it hasn't ever seen multi-character strings before, it will not be able to "understand" them.

You should train the model on multi-character images instead of single characters. Ideally, your training images should be close to what you need the model to recognize, or the training set should be vast (like Synth90k).
